### PR TITLE
Fix bug in gr_mat_move_row

### LINKED ISSUE #2510: `GR_MUST_SUCCEED` in `fmpz_lll`
**Describe the bug**
In Hecke, we see a bunch of failures when trying to update it to use FLINT 3.4.0, see https://github.com/thofma/Hecke.jl/pull/2095. All of the seem to be of the form `ERROR: Flint Exception (General error): GR_MUST_SUCCEED failure: /workspace/srcdir/flint-3.4.0/src/fmpz_lll/lll_d.c`

**Steps to reproduce**
Start Nemo.jl v0.53.0 and execute the following:
```julia
julia> A = ZZ[-1 -1 0 1 -1 1; -2 -1 2 1 0 0; 0 0 0 0 0 0; 0 -1 0 1 0 0; 2 1 0 -1 0 0; 0 1 2 -1 0 0; 0 0 1 0 0 0; -1 0 1 0 0 0; 1 0 0 0 0 0]
[-1   -1   0    1   -1   1]
[-2   -1   2    1    0   0]
[ 0    0   0    0    0   0]
[ 0   -1   0    1    0   0]
[ 2    1   0   -1    0   0]
[ 0    1   2   -1    0   0]
[ 0    0   1    0    0   0]
[-1    0   1    0    0   0]
[ 1    0   0    0    0   0]

julia> lll_with_transform(A)
ERROR: Flint Exception (General error):
GR_MUST_SUCCEED failure: /workspace/srcdir/flint-3.4.0/src/fmpz_lll/lll_d.c
Stacktrace:
 [1] flint_throw(err_type::Nemo.FlintExceptionType, cmsg::Cstring, va_list::Ptr{Nothing})
   @ Nemo ~/code/julia/Nemo.jl/src/Nemo.jl:296
 [2] lll_with_transform(x::ZZMatrix, ctx::LLLContext)
   @ Nemo ~/code/julia/Nemo.jl/src/flint/fmpz_mat.jl:962
 [3] lll_with_transform(x::ZZMatrix)
   @ Nemo ~/code/julia/Nemo.jl/src/flint/fmpz_mat.jl:960
 [4] top-level scope
   @ REPL[7]:1
```
The function is located at https://github.com/lgoettgens/Nemo.jl/blob/9ea61a43bf2f7ac5b65b70835d20baa6f682b97d/src/flint/fmpz_mat.jl#L959-L964.

**Expected behavior**
In Nemo v0.52.4 (which basically just differs in the used FLINT version, it used v3.3.1), one gets the following result:
```
julia> lll_with_transform(A)
([0 0 0 0 0 0; 0 0 0 0 0 0; 0 0 0 0 0 0; 0 0 0 0 0 0; 0 0 0 0 0 0; 0 0 1 0 0 0; -1 0 0 0 0 0; 0 -1 0 1 0 0; 0 0 0 0 -1 1], [0 0 1 0 0 0 0 0 0; 0 -1 0 1 -1 1 0 0 0; 0 1 0 0 1 0 -2 0 0; 0 0 0 1 1 0 -2 2 0; 0 0 0 0 0 0 -1 1 1; 0 0 0 0 0 0 1 0 0; 0 0 0 0 0 0 -1 1 0; 0 0 0 1 0 0 0 0 0; 1 0 0 -1 0 0 1 -1 0])
```

**System (please complete the following information):**
Version of FLINT: FLINT_jll v301.400.0+0, build from FLINT v3.4.0 without any patches
```julia
julia> Base.BinaryPlatforms.host_triplet()
"x86_64-linux-gnu-libgfortran5-cxx11-libstdcxx30-julia_version+1.12.2"
```

cc @thofma

### PR DESCRIPTION
**Pull request by fredrik-johansson**
Hopefully fixes #2510.

Also fixes ``fmpz_mat_is_reduced`` to not hang when checking the output. BTW, ``fmpz_mat_is_reduced`` returns false in flint-3.3 here, and I've made it return the same thing. Was this the intended behavior?

Unfortunately our test code for ``fmpz_lll`` seems to do a really poor job testing rank-deficient matrices.

### CODE REVIEW

**Comment by thofma** [comment]
I think the original code was never intended for the rank-deficient case. See https://github.com/flintlib/flint/pull/1168.

File: src/fmpz_mat/is_reduced.c [hunk 1]
```diff
@@ -55,7 +55,12 @@ fmpz_mat_is_reduced(const fmpz_mat_t A, double delta, double eta)
 
         gr_ctx_clear(ctx);
 
-        if (is_reduced != T_UNKNOWN)
+        if (is_reduced != T_UNKNOWN || prec >= exact_cutoff)
+            break;
+        /* Failure with the fmpq context implied that we attempted to divide
+           by an exactly zero GS norm; by the current definition, this
+           matrix is not reduced. */
+        if (prec >= exact_cutoff)
```
Comment (lgoettgens) [inline src/fmpz_mat/is_reduced.c:63]: This second if statement will never evaluate to true, as the condition is already checked in the previous one. Is this intended?

**Comment by lgoettgens** [comment]
I can verify that with this patch applied, the errors from https://github.com/thofma/Hecke.jl/pull/2095 disappear.

File: src/fmpz_mat/is_reduced.c (hunk 1 above)
Comment (fredrik-johansson) [reply src/fmpz_mat/is_reduced.c:63]: The statement was indeed duplicated; thanks for spotting.
