### PR TITLE
fix(fmpz): return exact size from fmpz_sizeinbase

### LINKED ISSUE #2638: fmpz_sizeinbase can be 1 too big
The return value from fmpz_sizeinbase can be 1 too big if b >= 3 and the value is stored internally as mpz_t.
This behavior is documented by GMP.

Flint 3.4.0 with GMP 6.3.0, on x64. Flint reports that 10^19-1 has 20 decimal digits.

### PR DESCRIPTION
**Pull request by edgarcosta**
GMP's mpz_sizeinbase may return a value 1 too big when the base is not a power of 2, so fmpz_sizeinbase inherited the same imprecision for large integers (e.g. fmpz_sizeinbase(10^19 - 1, 10) returned 20 instead of 19).

Detect the off-by-one by comparing |z| against b^(k-1) when b is not a power of 2 and k >= 2. The small-integer path and power-of-2 bases are already exact and left unchanged.

Strengthen the test to compare against the authoritative digit count from mpz_get_str and add a regression check for 10^19 - 1.

Fixes #2638.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
This will slow down applications where `fmpz_sizeinbase` is used to get a quick bound for the space one needs to allocate in a string, which is probably most of the current uses. If we make it exact, it should at least be $O(1)$ on average, with the exact computation done only when needed (for powers and near-powers of the base).

**Comment by fredrik-johansson** [comment]
The single-limb base 10 case could be sped up using the (currently private) function `n_nonzero_sizeinbase10` in https://github.com/flintlib/flint/blob/main/src/radix/get_str.c.

**Comment by edgarcosta** [comment]
I didnt see your second comment, but `n_nonzero_sizeinbase10` is static, and using it would require moving the helper + tables to a shared location

**Comment by fredrik-johansson** [comment]
Yes, it would require moving, to `ulong_extras` for example (it doesn't really need to be an inline function).

For the fast case maybe something like this (warning: untested) is a bit more efficient than the code in your latest commit:

    double lg = fmpz_dlog(x) * (b == 10 ? 0.43429448190325176 : 1 / log(b));
    double hi = lg * (1 + 1e-12);
    double lo = lg * (1 - 1e-12);

    if ((slong) lo == (slong) hi)
        return (slong) lo + 1;

File: src/fmpz/sizeinbase.c [hunk 1]
```diff
@@ -9,16 +9,56 @@
...
 size_t fmpz_sizeinbase(const fmpz_t f, int b)
 {
     fmpz d = *f;
+    mpz_srcptr z;
+    long e;
+    double s, lg;
+    slong lo, hi;
 
     if (!COEFF_IS_MPZ(d))
         return z_sizeinbase(d, b);
```
Comment (fredrik-johansson) [inline src/fmpz/sizeinbase.c:27]: Here you can use `n_nonzero_sizeinbase10` as well (or put a `n_nonzero_sizeinbase10` branch in `z_sizeinbase`).
