### PR TITLE
Correct FQ_DEFAULT_TYPE comparison in evaluation

### LINKED ISSUE #2046: `fq_default_poly_evaluate_fq_default` with context type `FMPZ_MOD` segfaults
The following code has a copy paste error:

```c
    else if (_FQ_DEFAULT_TYPE(ctx) == _FQ_DEFAULT_NMOD)
    {
        fmpz_mod_poly_evaluate_fmpz(res->fmpz_mod, f->fmpz_mod, a->fmpz_mod,
                                                        FQ_DEFAULT_CTX_FMPZ_MOD(ctx));
    }
```

https://github.com/flintlib/flint/blob/05340d2a7349761aff2cd3370810c93e2174ce46/src/fq_default_poly.h#L2053C1-L2057C6

Which leads to a segfault as the `FQ_DEFAULT_CTX_FMPZ_MOD` context type is never identified

### PR DESCRIPTION
**Pull request by GiacomoPope**
The method `fq_default_poly_evaluate_fq_default()` had an incorrect comparison for the default type, which lead to a segfault when using this method with type `fmpz_mod`.

This PR should fix the issue and hence fix #2046

### CODE REVIEW

**Comment by albinahlback** [comment]
Thanks, looks good! Do you agree @fredrik-johansson?

**Comment by GiacomoPope** [comment]
I don't know if I need to add tests to show that this is fixed? I've not contributed to flint before -- this was identified while working on python-flint.

**Comment by albinahlback** [comment]
Yes, it would be good with a test. Could you implement one? The tests are under `fq_default_poly/test`. You create a test file (in this case, `t-evaluate_fq_default.c`), and then include it in the main file `main.c` in the same directory. You can test that module with `make check MOD=fq_default_poly`.

**Comment by GiacomoPope** [comment]
Hi @albinahlback -- I attempted to write a test following your advice where I made a simple function which evaluates a polynomial `f(x)` at a point `a` twice and ensures the results match.

For `FQ_ZECH` and `NMOD` types this works. For `FQ_NMOD` i get a bus error. For `FQ` I get a segfault and for `FMPZ_MOD` I get incorrect values...

I can't tell if the function is more broken than I thought or if I've done something very stupid when writing the test

**Comment by GiacomoPope** [comment]
OK -- I had a few silly bugs along the way, but I think I now have a semi-decent check for all 5 fq_default types in place.

**Comment by albinahlback** [comment]
Thanks for the commit!

A couple of comments:
1. Could you stylize the comments as `/* comment */`?
2. Could you randomize even more? More specifically, could you randomize the extension degree? Randomization of the type is also nice, but not necessary.
3. What are you exactly testing? Obviously it checks that it doesn't crash, but apart from that it only seems to check that two consecutive evaluations yield the same result, no? My knowledge on finite fields is not the best, but wouldn't it be possible to check that the result is consistent with general algebraic rules like $\mathrm{eval}(p_{1}) \otimes \mathrm{eval}(p_{2}) = \mathrm{eval}(p_{1} \otimes p_{2})$, where `\otimes` is addition or multiplication?

**Comment by albinahlback** [comment]
> The actual test was copied from an exiting one:
> 
> https://github.com/flintlib/flint/blob/05340d2a7349761aff2cd3370810c93e2174ce46/src/fmpz_mod_poly/test/t-evaluate_fmpz.c#L43-L46

You only copied parts of that test. That part only checks aliasing, not other mathematical consistencies.

> I can randomise the type, but the idea was to ensure all 5 types were always captured.

It is better with randomization as you can change seeds etc. All types will be covered given large enough test multipliers.

> If you would prefer I can use the `fq_default_ctx_randtest()` and simply ask for a new random context for everything single call?

> Oh... Apparently https://flintlib.org/doc/fq_default.html#c.fq_default_ctx_randtest is in the documentation but not in the code?
>
> Should an issue be made for this?

Given that `fq_default_ctx_init_rand` or something similar does not exist, I think the current solution is good.

File: src/fq_default_poly/test/t-evaluate_fq_default.c [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+TEST_FUNCTION_START(fq_default_poly_evaluate, state)
+{
+    int i, k;
+    fmpz_t p;
+    fq_default_ctx_t ctx;
+
+    fmpz_init(p);
+
+    /* Repeat the whole test 10 times to capture different degrees */
+    for (i = 0; i < 10; i++)
```
Comment (albinahlback) [inline src/fq_default_poly/test/t-evaluate_fq_default.c:83]: Insert test multiplier here

File: src/fq_default_poly/test/t-evaluate_fq_default.c [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+    the terms of the GNU Lesser General Public License (LGPL) as published
+    by the Free Software Foundation; either version 3 of the License, or
+    (at your option) any later version.  See <https://www.gnu.org/licenses/>.
+*/
+
+#include "test_helpers.h"
+#include "fq_default_poly.h"
+
+/// Given a fq_default_ctx, compute two random polynomials f1, f2 and a 
+/// random element a, and ensure f1(a) * f2(b) == (f1 * f2)(a).
```
Comment (albinahlback) [inline src/fq_default_poly/test/t-evaluate_fq_default.c:16]: Commenting style

File: src/fq_default_poly/test/t-evaluate_fq_default.c [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+    fq_default_ctx_t ctx;
+
+    fmpz_init(p);
+
+    /* Repeat the whole test 10 times to capture different degrees */
+    for (i = 0; i < 10; i++)
+    {
+        /* Test FQ_ZECH type with GF(3^k), k < 12 */
+        k = n_randint(state, 12);
+        fmpz_set_ui(p, 3);
```
Comment (albinahlback) [inline src/fq_default_poly/test/t-evaluate_fq_default.c:87]: The problem here is that you are only able to capture bugs for cases on the form $3^k$. You should try to randomize this even more.

But be careful here since the `fq_zech` type does not like when you go big.

File: src/fq_default_poly/test/t-evaluate_fq_default.c [hunk 4]
```diff
@@ -0,0 +1,122 @@
...
+        fq_default_ctx_init_type(ctx, p, k, "x", 1);
+        test_eval_with_ctx(ctx, state);
+        fq_default_ctx_clear(ctx);
+
+        /* Test FQ_NMOD type with GF(163^k), k < 8  */
+        k = n_randint(state, 8);
+        fmpz_set_ui(p, 163);
+        fq_default_ctx_init_type(ctx, p, 3, "x", 2);
+        test_eval_with_ctx(ctx, state);
+        fq_default_ctx_clear(ctx);
```
Comment (albinahlback) [inline src/fq_default_poly/test/t-evaluate_fq_default.c:97]: `k` is not being used here

File: src/fq_default_poly/test/t-evaluate_fq_default.c [hunk 5]
```diff
@@ -0,0 +1,122 @@
...
+
+        /* Test FQ type with GF((2^127 - 1)^k), k < 8 */
+        k = n_randint(state, 8);
+        fmpz_set_str(p, "170141183460469231731687303715884105727", 10);
+        fq_default_ctx_init_type(ctx, p, 2, "x", 3);
+        test_eval_with_ctx(ctx, state);
+        fq_default_ctx_clear(ctx);
```
Comment (albinahlback) [inline src/fq_default_poly/test/t-evaluate_fq_default.c:104]: same here

File: src/fq_default_poly/test/t-evaluate_fq_default.c [hunk 6]
```diff
@@ -0,0 +1,122 @@
...
+
+        /* Test NMOD type with GF(65537) */
+        fmpz_set_ui(p, 65537);
+        fq_default_ctx_init_type(ctx, p, 1, "x", 4);
+        test_eval_with_ctx(ctx, state);
+        fq_default_ctx_clear(ctx);
```
Comment (albinahlback) [inline src/fq_default_poly/test/t-evaluate_fq_default.c:110]: Missing randomization.

File: src/fq_default_poly/test/t-evaluate_fq_default.c [hunk 7]
```diff
@@ -0,0 +1,122 @@
...
+
+        /* Test FMPZ_MOD type with GF(2^127 - 1) */
+        fmpz_set_str(p, "170141183460469231731687303715884105727", 10);
+        fq_default_ctx_init_type(ctx, p, 1, "x", 5);
+        test_eval_with_ctx(ctx, state);
+        fq_default_ctx_clear(ctx);
```
Comment (albinahlback) [inline src/fq_default_poly/test/t-evaluate_fq_default.c:116]: Missing randomization.

**Review by albinahlback — CHANGES_REQUESTED** [review]

File: src/fq_default_poly/test/t-evaluate_fq_default.c (hunk 1 above)
Comment (GiacomoPope) [reply src/fq_default_poly/test/t-evaluate_fq_default.c:83]: I purposefully didn't because the multiplier is in the inner test function. Would you like it here too? I was worried about having this multiplier squared would be an issue

File: src/fq_default_poly/test/t-evaluate_fq_default.c (hunk 7 above)
Comment (GiacomoPope) [reply src/fq_default_poly/test/t-evaluate_fq_default.c:116]: Is there an easy way in flint to request a random prime of bounded size?

File: src/fq_default_poly/test/t-evaluate_fq_default.c (hunk 2 above)
Comment (GiacomoPope) [reply src/fq_default_poly/test/t-evaluate_fq_default.c:16]: Should multi line comments be of the form

```c
\*
  Text
  Here
*\
```

File: src/fq_default_poly/test/t-evaluate_fq_default.c (hunk 7 above)
Comment (GiacomoPope) [reply src/fq_default_poly/test/t-evaluate_fq_default.c:116]: Ahh there's fmpz_randprime. I will use this.

File: src/fq_default_poly/test/t-evaluate_fq_default.c (hunk 1 above)
Comment (GiacomoPope) [reply src/fq_default_poly/test/t-evaluate_fq_default.c]: I added it in, feel free to ask me to remove it again

File: src/fq_default_poly/test/t-evaluate_fq_default.c (hunk 2 above)
Comment (GiacomoPope) [reply src/fq_default_poly/test/t-evaluate_fq_default.c]: I looked through the source code and tried to align the comment to what already exists

File: src/fq_default_poly/test/t-evaluate_fq_default.c (hunk 3 above)
Comment (GiacomoPope) [reply src/fq_default_poly/test/t-evaluate_fq_default.c]: For FQ_ZECH and FQ_NMOD I have two tests likely to pick each of these but allow fq_default to automatically select between these to avoid needing to be precise about when to use one or the other. Hopefully you are ok with what i have picked

File: src/fq_default_poly/test/t-evaluate_fq_default.c (hunk 2 above)
Comment (albinahlback) [reply src/fq_default_poly/test/t-evaluate_fq_default.c]: I don't think we have any strong opinions here. Thanks!

**Comment by GiacomoPope** [comment]
did you need anything else from me for this PR?

**Comment by albinahlback** [comment]
Sorry for the delay. Will respond in a couple of days.

**Comment by albinahlback** [comment]
Does it no longer check aliasing?

**Comment by GiacomoPope** [comment]
I'm not sure I understand

**Comment by albinahlback** [comment]
> I'm not sure I understand

We usually check aliasing, such as `fmpz_add(x, x, y)` works and is consistent with `fmpz_add(z, x, y)` (here `z` and `x` are two different instances). When I looked at it earlier, it looked like it had been removed.

**Comment by GiacomoPope** [comment]
You want the evaluation to check aliasing then? I can do this if you want I didn't intentionally add or remove anything though. Is the current test not sufficient?

**Comment by albinahlback** [comment]
> You want the evaluation to check aliasing then?

Since it was in the previous commit (and contained in similar tests), I would very much like that!

> I can do this if you want I didn't intentionally add or remove anything though.

Don't worry, didn't cross my mind.

> Is the current test not sufficient?

Well, it *should* work (since it is inherited from `fq_nmod_poly` etc.), but it is always good to have the test in the case that the infrastructure changes in the future.

**Comment by GiacomoPope** [comment]
```c
        /* Evaluate the polynomials f1, f2, f3 = f1 * f2 on the element a */
        fq_default_poly_evaluate_fq_default(c, f3, a, ctx);
        fq_default_poly_evaluate_fq_default(b, f2, a, ctx);
        fq_default_poly_evaluate_fq_default(a, f1, a, ctx);
```

this code is currently in place, it doesn't quite check that

```c
fq_default_poly_evaluate_fq_default(c, f1, a, ctx);
fq_default_poly_evaluate_fq_default(a, f1, a, ctx);
fq_default_equal(a, c, ctx);
```

But it implicitly checks this as it computes `c = f3(a)` and later `a = f1(a)` and ensures `f3(a) = f1(a) * f2(a)` -- would you like me to add more tests on top of what is here?

**Comment by albinahlback** [comment]
My bad. Yes, looks good! Will wait until Fredrik comes back from his vacation to see if he has any more opinions.

**Comment by fredrik-johansson** [comment]
Should be fine to merge after streamlining the test code on top of #2050.

**Comment by GiacomoPope** [comment]
Sorry for the delay in this, the new test is cleaner and uses the random context method from my other PR
